replicaCount: 1
rollingUpdatePartition: 0

awsHostNetworkEnabled: true

image:
  repository: "ankrnetwork/bas-template-bsc"
  pullPolicy: IfNotPresent
  tag: "devel"

alpineImage:
  repository: "alpine"
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

volumeSize: "500Gi"
enableInitEbsSnapshot: false
initSnapshotId: ""
storageClassName: "ebs-sc"

genesisInit:
  enabled: false
  url: https://github.com/binance-chain/bsc/releases/download/v1.1.2/mainnet.zip


# enable ServiceMonitor resources
enableMonitor: false

# Probe
enableStartupProbe: false
enableLivenessProbe: true

readinessProbe: {}
  # exec:
  #   command:
  #   - uname
  # failureThreshold: 1
  # successThreshold: 1
  # periodSeconds: 10
  # initialDelaySeconds: 10

resources:
  limits:
    cpu: "4"
    memory: 14Gi
  requests:
    cpu: 3400m
    memory: 12Gi

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

nodeSelector: {}

tolerations: []

affinity: {}

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

pvcAutoresizer:
  annotations: {}
      #resize.topolvm.io/increase: 250Gi


securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

EnableSnapshotDatabase: true

EnableDiskWarmUp: true

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

configPath: "a-config/config/*"
enablesecretStore: false
secretStoreRef:
  enable: false
  name: "bnbchain-secrets"
  kind: "SecretStore"
service:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-subnets: subnet-0224d90d23914fcdd,subnet-0aef1c93b03c50f48,subnet-0b430a213af598038
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: instance
    service.beta.kubernetes.io/aws-load-balancer-scheme: internal
