image:
  pullPolicy: Always
  repository: ghcr.io/bnb-chain/greenfield-challenger
  tag: 0.0.2
configMaps:
  config.json:
    data:
      config.json: |-
        {
          "greenfield_config": {
            "key_type": "local_private_key",
            "aws_region": "",
            "aws_secret_name": "",
            "aws_bls_secret_name": "",
            "private_key": "xxxxx",
            "bls_private_key": "xxxxx",
            "rpc_addrs": [
              "gnfd-testnet-fullnode-tendermint-us.bnbchain.org"
            ],
            "chain_id_string": "greenfield_5600-1",
            "gas_limit": 100000,
            "fee_amount": "500000000000000",
            "fee_denom": "BNB",
            "no_simulate": true,
            "deduplication_interval": 100
          },
          "log_config": {
            "level": "DEBUG",
            "filename": "",
            "max_file_size_in_mb": 0,
            "max_backups_of_log_files": 0,
            "max_age_to_retain_log_files_in_days": 0,
            "use_console_logger": true,
            "use_file_logger": false,
            "compress": false
          },
          "admin_config": {
            "listen_addr": "0.0.0.0:8080"
          },
          "db_config": {
            "dialect": "mysql",
            "db_path": "tcp(xxxx:3306)/testnet_cedar_greenfield_challenger?charset=utf8&parseTime=True&loc=Local",
            "username": "xxxxx",
            "password": "xxxxx",
            "key_type": "local_private_key",
            "aws_region": "",
            "aws_secret_name": "",
            "max_idle_conns": 20,
            "max_open_conns": 40,
            "debug_mode": true
          },
          "alert_config": {
            "enable_alert": false,
            "enable_heart_beat": false,
            "interval": 300,
            "identity": "your_service_name",
            "telegram_bot_id": "your_bot_id",
            "telegram_chat_id": "your_chat_id",
            "balance_threshold": "1000000000000000000",
            "sequence_gap_threshold": 10
          }
        }
configMapsMountPath: /opt/app/config/
containers:
  env:
    - name: CONFIG_TYPE
      value: local
    - name: AWS_REGION
      value: ""
    - name: AWS_SECRET_KEY
      value: ""
    - name: CONFIG_FILE_PATH
      value: /opt/app/config/config.json
  logsMountPath: /challenger/logs/
resources:
  limits:
    cpu: "2"
    memory: 4000Mi
  requests:
    cpu: 200m
    memory: 256Mi
service:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  type: ClusterIP