apiVersion: v1
kind: Service
metadata:
  name: {{ include "gnfd-relayer.fullname" . }}
  labels:
    {{- include "gnfd-relayer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- toYaml .Values.service.ports | nindent 4 }}
  selector:
    {{- include "gnfd-relayer.selectorLabels" . | nindent 4 }}
