apiVersion: v2
name: gnfd-relayer
description: A Helm chart for gnfd-relayer app

type: application

version: 0.2.2

dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
