{{- if .Values.enableConfigMapInit -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gnfd-validator.fullname" . }}-config
  labels:
    {{- include "gnfd-validator.labels" . | nindent 4 }}
data:
{{ (.Files.Glob .Values.configPath).AsConfig | indent 2 }}
{{- end }}
