apiVersion: v1
kind: Service
metadata:
  name: {{ include "gnfd-challenger.fullname" . }}
  labels:
    {{- include "gnfd-challenger.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- toYaml .Values.service.ports | nindent 4 }}
  selector:
    {{- include "gnfd-challenger.selectorLabels" . | nindent 4 }}
