apiVersion: v2
name: gnfd-challenger
description: A Helm chart for gnfd-challenger application

type: application

version: 0.0.1

dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
